###### Categories ######

### Listar ###
GET http://localhost:3000/categories

### Ler uma category ###
GET http://localhost:3000/categories/390102bf-c294-4290-aacf-18107718ad9b

### Ler inválido ### 
GET http://localhost:3000/categories/fake-id

### Criar uma categoria ###
POST http://localhost:3000/categories
Content-Type: application/json

{
    "name": "Movie 1"
}

### Alterar uma categoria ###
PUT http://localhost:3000/categories/390102bf-c294-4290-aacf-18107718ad9b
Content-Type: application/json

{
    "name": "Movie1111"
}

### Erro na atualização - fake-id ###
PUT http://localhost:3000/categories/fake-id
Content-Type: application/json

{
    "name": "Movie1111"
}

### Exclusão de categoria ###
DELETE http://localhost:3000/categories/51dde939-d315-44b6-a321-6795550527af
Content-Type: application/json



###### Cast Members ######

### Listar ###
GET http://localhost:3000/cast-members

### Buscar por type ###
GET http://localhost:3000/cast-members?filter[type]=2&page=1&per_page=15

### Buscar por name e type ###
GET http://localhost:3000/cast-members?filter[name]=MaRiA&filter[type]=1&page=1&per_page=15

### Ler inexistente com id válido ###
GET http://localhost:3000/cast-members/17b1a2ec-15aa-4f89-ab68-495d157ab999

### Id inválido ###
GET http://localhost:3000/cast-members/fake-id

### criar cast member ###
POST http://localhost:3000/cast-members
Content-Type: application/json

{
    "name": "John Doe",
    "type": 2
}

### alterar cast member ###
PUT http://localhost:3000/cast-members/f860becb-7b84-40f7-86f0-abae52da2b1b
Content-Type: application/json

{
    "name": "Mary Doe",
    "type": 2
}

### alterar id inválido ###
PUT http://localhost:3000/cast-members/fake-id
Content-Type: application/json

{
    "name": "Error"
}

### excluir ###
DELETE http://localhost:3000/cast-members/908573a1-ff94-4b0c-867c-7043d1a0fa16
Content-Type: application/json
