GET http://localhost:3000/categories

###

GET http://localhost:3000/categories/390102bf-c294-4290-aacf-18107718ad9b


###

POST http://localhost:3000/categories
Content-Type: application/json

{
    "name": "Movie 1"
}

###

PUT http://localhost:3000/categories/390102bf-c294-4290-aacf-18107718ad9b
Content-Type: application/json

{
    "name": "Movie1111"
}

###

DELETE http://localhost:3000/categories/51dde939-d315-44b6-a321-6795550527af
Content-Type: application/json
